FROM python:3.12-slim

WORKDIR /app

COPY requirements-prod.txt .

RUN pip install --no-cache-dir -r requirements-prod.txt

COPY . .

CMD ["sh","-c","streamlit run streamlit_app.py --server.port=${PORT:-10000} --server.address=0.0.0.0"]